image: eosio/key-value-example:v0.2.0

ports:
- port: 3000
  onOpen: ignore
- port: 8080
  onOpen: open-preview
- port: 8888
  onOpen: ignore
- port: 9876
  onOpen: ignore

tasks:
- before: yarn
  command: yarn run serveInGitPod
- before: chmod 755 $PWD/docker/deploy_contracts.sh
  command: $PWD/docker/deploy_contracts.sh "" IS_GITPOD
